# API Contract for Physical AI Book Authentication and Personalization

openapi: 3.0.0
info:
  title: Physical AI Book API
  version: 1.0.0
  description: API contracts for authentication and personalization features of the Physical AI Book

# Note: Since this is a static site, these endpoints represent client-side API calls
# to better-auth and other client-side services

paths:
  /api/auth/signup:
    post:
      summary: User registration
      description: Register a new user and collect their software/hardware background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
                - softwareBackground
                - hardwareBackground
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
                name:
                  type: string
                  description: User's display name
                softwareBackground:
                  type: string
                  description: User's software background and experience
                hardwareBackground:
                  type: string
                  description: User's hardware background and experience
      responses:
        '200':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '409':
          description: User already exists

  /api/auth/login:
    post:
      summary: User login
      description: Authenticate user and return session token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                    description: Session token for client-side storage
        '401':
          description: Invalid credentials

  /api/auth/profile:
    get:
      summary: Get user profile
      description: Retrieve current user's profile information
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Not authenticated
    put:
      summary: Update user profile
      description: Update user's profile information including background and preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Not authenticated

  /api/content/personalize:
    post:
      summary: Get personalized content
      description: Retrieve content adapted based on user's profile and preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - chapterId
                - preferences
              properties:
                chapterId:
                  type: string
                  description: ID of the chapter to personalize
                preferences:
                  type: object
                  description: User's preferences for content adaptation
      responses:
        '200':
          description: Personalized content returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Personalized content
                  fallback:
                    type: boolean
                    description: Whether fallback content was used

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
        email:
          type: string
          format: email
          description: User's email address
        name:
          type: string
          description: User's display name
        softwareBackground:
          type: string
          description: User's software background and experience
        hardwareBackground:
          type: string
          description: User's hardware background and experience
        preferences:
          type: object
          description: User's content preferences
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp
        lastLogin:
          type: string
          format: date-time
          description: Last login timestamp
    UserUpdate:
      type: object
      properties:
        name:
          type: string
          description: Updated display name
        softwareBackground:
          type: string
          description: Updated software background
        hardwareBackground:
          type: string
          description: Updated hardware background
        preferences:
          type: object
          description: Updated content preferences

# Note: This is a contract for client-side API interactions in a static site context
# Actual implementation will use better-auth client-side functions