openapi: 3.0.0
info:
  title: Authentication and User Profiling API
  description: API for user authentication and profile management
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Development server
  - url: https://api.physicalai-book.com/api
    description: Production server

paths:
  /auth/register:
    post:
      summary: Register a new user with profile information
      description: Creates a new user account and associated profile with background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - software_experience
                - hardware_experience
                - background_preference
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
                software_experience:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  description: User's software background level
                hardware_experience:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  description: User's hardware background level
                background_preference:
                  type: string
                  enum: [software, hardware, mixed]
                  description: User's preferred focus area
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "User registered successfully"
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid email format"
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Email already registered"

  /auth/login:
    post:
      summary: Authenticate user and create session
      description: Authenticates user credentials and creates a session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Login successful"
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid email or password"

  /auth/logout:
    post:
      summary: Logout user and destroy session
      description: Destroys the current user session
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Logout successful"

  /auth/profile:
    get:
      summary: Get current user's profile
      description: Retrieves the profile information for the authenticated user
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  profile:
                    $ref: '#/components/schemas/UserProfile'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Not authenticated"
    put:
      summary: Update current user's profile
      description: Updates the profile information for the authenticated user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                software_experience:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  description: User's software background level
                hardware_experience:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  description: User's hardware background level
                background_preference:
                  type: string
                  enum: [software, hardware, mixed]
                  description: User's preferred focus area
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  profile:
                    $ref: '#/components/schemas/UserProfile'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Not authenticated"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique user identifier
        email:
          type: string
          format: email
          description: User's email address
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
        is_active:
          type: boolean
          description: Account active status
        email_verified:
          type: boolean
          description: Email verification status

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique profile identifier
        user_id:
          type: string
          format: uuid
          description: Reference to the user
        software_experience:
          type: string
          enum: [beginner, intermediate, advanced]
          description: User's software background level
        hardware_experience:
          type: string
          enum: [beginner, intermediate, advanced]
          description: User's hardware background level
        background_preference:
          type: string
          enum: [software, hardware, mixed]
          description: User's preferred focus area
        created_at:
          type: string
          format: date-time
          description: Profile creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last profile update timestamp