#!/usr/bin/env node

// Sidebar auto-generation script for Physical AI Book
// This script scans the docs directory and generates a sidebar structure

const fs = require('fs');
const path = require('path');

// Configuration
const DOCS_DIR = path.join(__dirname, '../docs');
const OUTPUT_FILE = path.join(__dirname, '../sidebars.js');

// File extensions to include
const INCLUDE_EXTENSIONS = ['.md', '.mdx'];

// Directories to exclude
const EXCLUDE_DIRS = ['node_modules', '.git', '.github'];

// Function to check if a directory should be included
function shouldIncludeDir(dirName) {
  return !EXCLUDE_DIRS.includes(dirName);
}

// Function to check if a file should be included
function shouldIncludeFile(fileName) {
  return INCLUDE_EXTENSIONS.some(ext => fileName.toLowerCase().endsWith(ext));
}

// Function to get the title from a markdown file
function getTitleFromMarkdown(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    // Look for the title in the frontmatter
    const titleMatch = content.match(/title:\s*['"]([^'"]+)['"]/i);
    if (titleMatch) {
      return titleMatch[1];
    }

    // If no frontmatter title, look for the first heading
    const headingMatch = content.match(/^#\s+(.+)$/m);
    if (headingMatch) {
      return headingMatch[1].trim();
    }

    // If no heading, use the filename
    const fileName = path.basename(filePath, path.extname(filePath));
    return formatTitle(fileName);
  } catch (error) {
    console.warn(`Could not read title from ${filePath}:`, error.message);
    const fileName = path.basename(filePath, path.extname(filePath));
    return formatTitle(fileName);
  }
}

// Function to format a title from a filename
function formatTitle(fileName) {
  // Replace hyphens and underscores with spaces
  let title = fileName.replace(/[-_]/g, ' ');
  // Capitalize first letter of each word
  return title.replace(/\b\w/g, l => l.toUpperCase());
}

// Function to recursively scan a directory and build sidebar structure
function scanDirectory(dirPath, basePath = '') {
  const items = [];

  const entries = fs.readdirSync(dirPath);

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry);
    const relativePath = path.join(basePath, entry).replace(/^\/+/, '');

    const stat = fs.statSync(fullPath);

    if (stat.isDirectory() && shouldIncludeDir(entry)) {
      // Create a category for the directory
      const categoryItems = scanDirectory(fullPath, relativePath);
      if (categoryItems.length > 0) {
        items.push({
          type: 'category',
          label: formatTitle(entry),
          items: categoryItems
        });
      }
    } else if (stat.isFile() && shouldIncludeFile(entry)) {
      // Add the file to the items list
      const fileRelativePath = relativePath.replace(/\.(md|mdx)$/, '');
      items.push(fileRelativePath);
    }
  }

  return items;
}

// Function to generate sidebar content
function generateSidebarContent(sidebarStructure) {
  const sidebarContent = `// @ts-check

// This file is auto-generated by the sidebar generation script
// Do not edit manually. Instead, run the script to regenerate.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    ${generateSidebarItems(sidebarStructure.slice(1), 4)}  // Skip 'intro' as it's hardcoded
  ],
};

module.exports = sidebars;
`;

  return sidebarContent;
}

// Function to generate sidebar items recursively
function generateSidebarItems(items, indentLevel) {
  const indent = ' '.repeat(indentLevel);
  let result = '';

  for (const item of items) {
    if (typeof item === 'string') {
      result += `${indent}'${item}',\n`;
    } else if (item.type === 'category') {
      result += `${indent}{\n`;
      result += `${indent}  type: 'category',\n`;
      result += `${indent}  label: '${item.label}',\n`;
      result += `${indent}  items: [\n`;
      result += generateSidebarItems(item.items, indentLevel + 4);
      result += `${indent}  ],\n`;
      result += `${indent}},\n`;
    }
  }

  return result;
}

// Main function
function main() {
  console.log('Starting sidebar auto-generation...');

  try {
    // Scan the docs directory
    const sidebarStructure = scanDirectory(DOCS_DIR);
    console.log('Directory scan completed. Found structure:', JSON.stringify(sidebarStructure, null, 2));

    // Generate sidebar content
    const sidebarContent = generateSidebarContent(sidebarStructure);

    // Write to the output file
    fs.writeFileSync(OUTPUT_FILE, sidebarContent);
    console.log(`Sidebar successfully generated and written to ${OUTPUT_FILE}`);

    console.log('Sidebar auto-generation completed successfully!');
  } catch (error) {
    console.error('Error during sidebar auto-generation:', error);
    process.exit(1);
  }
}

// Run the script if this file is executed directly
if (require.main === module) {
  main();
}

module.exports = {
  scanDirectory,
  getTitleFromMarkdown,
  formatTitle,
  generateSidebarContent
};